services:
  backend:
    build:
      context: ./api_flask
    ports:
      - "8121:8081"  # Isso mapeia a porta 8081 no container para a 8121 no host
    volumes:
      - ./api_flask:/app
    environment:
      - FLASK_ENV=development
    networks:
      - my-network

  frontend:
    build:
      context: ./front-end/project-interface
    ports:
      - "8120:80"  # Porta 8120 no host mapeada para a 80 no container
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

